<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Aion2Helper</RootNamespace>
    <AssemblyName>Aion2Helper</AssemblyName>
    <PackageId>Aion2Helper</PackageId>
    <Product>Aion2 Helper</Product>
    <Company>Aion2 Helper</Company>
    <Copyright>Copyright (C) 2024</Copyright>
    <Version>1.0.0.0</Version>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.11.0.20250507" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="MySqlConnector" Version="2.3.7" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="System.Windows.Forms.DataVisualization" Version="1.0.0-prerelease.20110.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <!-- 排除子项目文件夹 -->
  <ItemGroup>
    <Compile Remove="Aion2Helper.Core\**" />
    <EmbeddedResource Remove="Aion2Helper.Core\**" />
    <None Remove="Aion2Helper.Core\**" />
    <Compile Remove="Aion2Helper.Admin\**" />
    <EmbeddedResource Remove="Aion2Helper.Admin\**" />
    <None Remove="Aion2Helper.Admin\**" />
  </ItemGroup>

  <!-- 自动复制 images 目录到输出目录 -->
  <ItemGroup>
    <Content Include="images\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="Aion2Helper.Core\Aion2Helper.Core.csproj" />
  </ItemGroup>

</Project>